name: Unit test and code coverage

on:
  push:
    branches:
      - dev
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches:
      - dev
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        auto-activate-base: true
    - shell: bash -l {0}
      run: |
        conda info
        conda list
    - name: Install PyTorch
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          pip install torch==1.7.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
        else
          pip install torch==1.7.0
        fi
      shell: bash
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest coverage coveralls
        conda install -c conda-forge icu
        conda install -c conda-forge pyicu
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install "h5py>=2.10.0,<3" "tensorflow>=2.3.1,<3"
        pip install deepcut
        pip install .[full]
    - name: Test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        coverage run -m unittest discover
        CI_BRANCH=${GITHUB_REF#"ref/heads"} COVERALLS_REPO_TOKEN=${{ secrets.COVERALLS_REPO_TOKEN }} coveralls
