name: PyPI Unit test

on:
  schedule:
    - cron: '0 0 * * *' # Once per day

jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install deepcut tltk
        pip install -r https://raw.githubusercontent.com/PyThaiNLP/pythainlp/dev/docker_requirements.txt
        pip install pythainlp[full]
        python -m nltk.downloader omw-1.4
    - name: Test
      run: |
        mkdir pythainlp_test
        cd pythainlp_test
        pip download --no-binary=:all: --no-dependencies pythainlp
        file="find . -name *.tar.gz"
        file=$(eval "$file")
        tar -xvzf $file --one-top-level
        second="/"
        path=${file//.tar.gz/$second}
        cd $path
        ls
        cd tests
        mkdir tests
        mv data tests/
        python -m unittest discover
