name: Windows Unit test and code coverage

on:
  push:
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches:
      - dev
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        auto-activate-base: false
        auto-update-conda: true
    - shell: powershell
      run: |
        conda info
        conda list
    - name: Install PyTorch
      shell: powershell
      run: |
        pip install torch==1.7.0
    - name: Install dependencies
      shell: powershell
      run: |
        python -m pip install --upgrade pip
        pip install pytest coverage coveralls
        conda install -c conda-forge icu
        conda install -c conda-forge pyicu
        pip install -r docker_requirements.txt
        pip install deepcut
        pip install .[full]
        python -m nltk.downloader omw-1.4
    - name: Test
      shell: powershell
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_SERVICE_NAME: github
      run: |
        coverage run -m unittest discover
        coveralls
